### ISSUE TITLE
Hierarchical JSON not handled correctly and Increasing memory footprint

### ISSUE THREAD

**Issue by kjkurien** [SteveSanderson/knockout.mapping#119]
Firstly, if this is the wrong forum to post this, please let me the correct forum to raise such issues.(pretty new to KO and Mapping).
- I have hierarchical JSON structure that differs after every new JSON from the server side. Given my template, this does not adequately show model update.
  After troubleshooting, I noticed the mapping plugin does not correctly map child elements(or perhaps I am doing it incorrectly)
- I can also track the memory keeps growing for every update in the datamodel.

Any help will be greatly appreciated.

This simple test is up on JSFiddle http://jsfiddle.net/Bru5a/1/

Here is my view

```
<div id="view">
Test Case
<ul> <li> Click Second then Third </li>
      <li> JSFiddle Run - To Reset and Click Third and Second </li>
</ul>
The behavior is different depending on the order you load the model.

Testing  <a href="#" id="first">First</a>
<a href="#" id="second">Second</a>
<a href="#" id="third">Third</a>
<p data-bind="text: name"></p>

    <div data-bind="if: $data.child">    
         <b data-bind="text: child.name"></b>
         <div data-bind="if: child.sub">
             <b data-bind="text: child.sub.name"></b>
         </div>
    </div>
</div>
```

Here is my Javascript:

<pre><code>
var BaseModel = function(om) {
        ko.mapping.fromJS(om, {}, this);
    };
    var resourceModel = null;
    function applyJson(json) {
        try {
        if(resourceModel){
            ko.mapping.fromJS(json, {} ,resourceModel);
        } else {
            resourceModel = new BaseModel(json);
            ko.applyBindings(resourceModel, $("#view")[0]);
        }
        } catch(e) {
            alert(e);
        }
    }
    function loadFirst() {
        var json = { "name" : "1",
                     "child" : {
                         "name": "Child One"
                     }
        };
        applyJson(json);
    }
    function loadSecond() {
         var json = { "name" : "2"  };
        applyJson(json);
    }
    function loadThird() {
         var json = { "name" : "3",
                     "child" : {
                         "name": "Child Three",
                        "sub" : {
                             "name" : "Third Sub Child"

                         }
                     }
        };
        applyJson(json);
    }
    $(document).ready(function () {
        
        $("#second").click(function(){
                loadSecond();
                });
        $("#third").click(function(){
            loadThird();
            });
        $("#first").click(function(){
            loadFirst();
            });
        });​
</code></pre>

**Comment by sagacity** [comment]
This will not work because when you are rendering your template `child.sub` doesn't even exist yet, so your template will not have a dependency on this property. If you want to handle a situation like this you would need to initialize your model with a value of `null` for sub, so it can be properly mapped to an observable.

What you can do is, in the mapping options for your BaseModel (i.e. the options passed into `ko.mapping.fromJS`), have a create callback for `child` in which you create a ChildModel. Then, within your childmodel you could have a `create` callback for `sub`.

I'm not sure why these properties aren't simply called `child` all the way down though, but that should get you started.
