### ISSUE TITLE
toJSON has no way to pass in stringify options

### ISSUE THREAD

**Issue by spring1975** [SteveSanderson/knockout.mapping#155]
Using knockout's toJSON, you can pass in stringify formatting options.

`ko.toJSON(viewModel, null, 2}`

Using the same syntax with the mapping toJSON, those options are ignored.

`ko.mapping.toJSON(viewModel, null, 2)`

Watching the plugin in Chrome's developer tools, I see by the time the mapping plugin gets to the line where it actually calls the stringify function, the options are lost.

Maybe this is intentional, since most times this would be used to output to a server and therefore you'd want it minified anyway?

Though, it's certainly nice to see the formatted output while debugging.  Maybe I'm just missing how I should be passing in those options?

**Comment by sagacity** [comment]
The mapping plugin's `toJSON` syntax is currently different from knockout already, because you can provide an options object indicating which fields to ignore etc.

Formatting options could certainly be added, but you could also just do: `ko.toJSON(ko.mapping.toJS(....), null, 2)` to get what you want.

If you want to add the formatting options as third and fourth parameters to `ko.mapping.toJSON` I certainly would accept a pull request, of course :)

**Comment by spring1975** [comment]
Cool. I may do that. Thanks for the work around in the meantime.
