### ISSUE TITLE
Stack overflow when mapping an already mapped object

### ISSUE THREAD

**Issue by chitza** [SteveSanderson/knockout.mapping#160]
When mapping (by mistake) an already mapped object, the function `extendObject` enters in a recursive loop causing it to fill the call stack (RangeError: Maximum call stack size exceeded / too much recursion).

WARNING: Running this fiddle could cause the target Chrome tab to crash:
An example can be found here: http://jsfiddle.net/chitza/ysNWH/

``` javascript
//map once
var model = ko.mapping.fromJS({ foo: 'bar' });

//map again, by mistake, using model as data
model = ko.mapping.fromJS(model);

//this causes an infinite recursion
ko.mapping.fromJS({ foo: 'baz'}, model);
```

I managed to solve my problem by checking if the model is already mapped (using `ko.mapping.isMapped`) but unfortunately I don't have a fix for the mapping plugin this at the moment so I'm hoping someone could provide one.

This happens in version 2.4.1.

**Comment by skmasq** [comment]
I have the same problem, I have two identical models created at start and when I want to cancel changes to one of them I use mapping to replace values, this causes stack overflow.

Here is simplyfied version how I get maximum call stack - http://jsfiddle.net/skmasq/REQnt/

I found a way to solve this by assigning same mapping options, but with large objects and data sets this instantly crashes browser.

**Comment by alecola** [comment]
same problem here... Any fix?

**Comment by chitza** [comment]
Before mapping, check if the model is already mapped and do nothing - you can use `ko.mapping.isMapped`.

**Comment by alecola** [comment]
Hi, thanks for reply. Here is my code fragment:

```
    // DECLARATION
    //
    var MyViewModel = function() {
        var self = this;

        self.firstObject = null;
        ...
        self.updateFirstObject = function(newData) {
            ko.mapping.fromJS(newData, self.firstObject);
        }
    }

    // INITIALIZATION
    //
    myViewModel = new MyViewModel();
    myViewModel.firstObject = ko.mapping.fromJS(someData);
    ...
    ko.applyBindings(myViewModel);


    // LATER, AFTER SOME NEW DATA HAVE ARRIVED VIA AJAX:
    //
    <call the updateFirstObject function: gives the error>
```

If I don't do anything since the object is already mapped, how do I update it? If I write:

```
    self.firstObject = ko.mapping.fromJS(newData);
```

does not work. Thanks again,
//ale

**Comment by chitza** [comment]
I've used the example you provided and it seems to work just fine for me...
See this bin: http://jsbin.com/ARePuVUV/3

**Comment by alecola** [comment]
Yes you are right, I forgot to mention that for small objects it works fine. However, in my case firstObject is a complex object with several properties and other nested objects. So I guess that I have two alternatives:
1) reduce the complexity of the object
2) controlling the mapping with some mapping options, because not every single nested object has to be treated as an observable. Maybe this helps in reducing the execution complexity of the mapping function...
Thanks again for your help,
//ale

**Comment by alecola** [comment]
Ok, seems to work. The problem was the following:

I am calling the updateFirstObject passing newData, where newData is a json string read from a  text file (in my app, I can "export" the viewmodel on a text file, as a big json string, and then "reimport" it). However, this text file containing the exported viewmodel had been previously created using `ko.toJSON({ savedObj: self.firstObject})` instead of `ko.mapping.toJSON({ savedObj: self.firstObject})` . This caused an unwanted `__ko_mapping__` section to be present in the text file. I just removed that, and seems to work.
From now on I will always remember very well what is the difference between `ko.toJSON` and `ko.mapping.toJSON` =)
Thanks again for your help,
//ale

**Comment by chitza** [comment]
I've made the same confusion about `.toJSON` myself :)

**Comment by chitza** [comment]
I'll close the issue it since I believe we can both agree it's not the plugin's fault.
