### ISSUE TITLE
toJS should remove __ko_mapping__

### ISSUE THREAD

**Issue by abp** [SteveSanderson/knockout.mapping#2]
Shouldn't toJS on an object build by fromJS remove the **ko_mapping** property from the resulting object? For now i use the ignore option to exclude that field.

**Comment by sagacity** [comment]
Yes, it should. We should probably ignore it by default, but simply using the ignore option is the way to go.

**Comment by abp** [comment]
Ok, it was a little annoying at first. But because this is a very early version i thought it could be a bug.

What could the mapping be used for on the resulting object? I mean, why do you prefer to keep it instead of ignoring it by default?

**Comment by sagacity** [comment]
There is absolutely no reason you would need it, it's just a bug. I hadn't fixed it yet because I'm not sure if we need the mapping.toJS when there's already a toJS in ko itself. Once that gets the 'ignore' functionality I can probably remove it from the mapping plugin.

But thanks for noticing though, I'll keep this issue open for now so we can properly handle it later.

**Comment by sagacity** [comment]
This is now fixed.
