### ISSUE TITLE
Differenciate between create/update and createItem/updateItem

### ISSUE THREAD

**Issue by bikeshedder** [SteveSanderson/knockout.mapping#35]
All in all I would prefer if create/update would not behave different for arrays than for normal scalars:

```
create: receives the entire source data/array as options.data
update: receives the target data/array as target and the source data/array as options.data
```

Since most use cases will probably want to perform a simple create/update per item, two extra methods could be introduced:

```
createItem: behaves the same as the current create function for arrays
updateItem: behaves the same as the current update function for arrays
```

When overwriting the normal update/create methods for arrays one must take care to implement the key logic, but it the end it would make it possible to perform extremely powerful mappings.

Example:

```
source: {"foo": {...fooProps...}, "bar": {...barProps...}}
target: [{"name": "foo", ...fooProps...}, {"name": "bar", ...barProps...}]
```

In an application I'm currently writing I wanted to do exactly this but had to change the server return value to the target array because I was not able to map objects to array properties of the target model. With the proposed change such mappings are possible and the API becomes much more logical.

**Comment by sagacity** [comment]
If the create callback is changed like you propose (i.e. providing the source array), what would be the additional benefit of the createItem/updateItem calls? What additional benefit would they bring?

I mean, since the create callback requires you to return a 'created' object, would that not be already the place to do your more complex mapping as in the example?

**Comment by bikeshedder** [comment]
Without the createItem/updateItem callback the original "key" callback would be rendered almost useless as it could not be used for custom item mappings (but with standard array mapping) anymore.

**Comment by sagacity** [comment]
That's true, since the key callback assumes that the key property can be found in both mapped and unmapped objects.
I'm still a bit hazy on what the exact sequence of callbacks would be in your proposal. Could you give an indication what your source, target and mapping options would look like in an 'ideal' situation?

**Comment by sagacity** [comment]
Talked on Skype, and concluded this idea is not necessary to implement.
