### ISSUE TITLE
Suspicious behaviour of update callback

### ISSUE THREAD

**Issue by Anber** [SteveSanderson/knockout.mapping#37]
```
var someObjectModel = function(data) {
    ko.mapping.fromJS(data, {}, this);
}

var mapping = {
    'prop': {
        update: function(options) {
            var res = options.data ? new someObjectModel(options.data) : null;
            return ko.observable(res);
        }
    }
}

var obj_1 = {
    prop: null
};

var obj_2 = {
    prop: {}
};

var viewModel_1 = ko.mapping.fromJS(obj_1, mapping);
var viewModel_2 = ko.mapping.fromJS(obj_2, mapping);

console.log(typeof viewModel_1.prop, typeof viewModel_2.prop); // function function — Ok
console.log(typeof viewModel_1.prop(), typeof viewModel_2.prop()); // function object — Bug?
```

But «typeof viewModel_1.prop()» returns «object» if replace «update» on «create».

**Comment by Anber** [comment]
If it's still a bug.

**Comment by sagacity** [comment]
Anber, the idea is that the update callback does NOT return an observable, but just a regular object. If you change your code to do that instead, does it solve your problem?

**Comment by Anber** [comment]
After remove ko.observable I can't subscribe to changes.

```
var someObjectModel = function(data) {
    ko.mapping.fromJS(data, {}, this);
}

var mapping = {
    'prop': {
        update: function(options) {
            var res = options.data ? new someObjectModel(options.data) : null;
            return res;
        }
    }
}

var obj_1 = {
    prop: null
};

var obj_2 = {
    prop: {}
};

var viewModel_1 = ko.mapping.fromJS(obj_1, mapping);
var viewModel_2 = ko.mapping.fromJS(obj_2, mapping);

console.log(typeof viewModel_1.prop.subscribe); // function
console.log(typeof viewModel_2.prop.subscribe); // undefined
```

I don't use this, but I found it strange.

**Comment by sagacity** [comment]
You can't subscribe in the second case because you are returning a 'new someObjectModel' object, which I'm assuming does not have a subscribe method?

**Comment by Anber** [comment]
How right way to track changes in this case? Implement subscribe in someObjectModel?
Without ko.observable viewModel_2.prop don't work in binding.

**Comment by sagacity** [comment]
Can you put a more detailed example on jsfiddle?

**Comment by Anber** [comment]
http://jsfiddle.net/6L96F/1/

**Comment by sagacity** [comment]
You are trying to bind the entire 'prop' object to a span. This is why it is (correctly) showing: [Object object].

**Comment by Anber** [comment]
But content not change on update 'prop'.
Instead 'text' binding may be a 'if'.

**Comment by Anber** [comment]
For example

```
<!-- ko if: User -->
    Hi, <span data-bind="text:User.Login"></span>
<!-- /ko -->
<!-- ko notif: User -->
    Welcome! Sign in or register.
<!-- /ko -->
```

Where 'User' can be null or an object.

**Comment by sagacity** [comment]
Ah, right. The reason it does not update is because in your update callback you are overwriting the entire object with a new model. Therefore, the original 'User' model gets replaced by another 'User' model entirely! This new model is not bound to the template and KO does not rerender your template.

**Comment by Anber** [comment]
In this case need wrap User in ko.observable, but it is not working properly.

**Comment by sagacity** [comment]
You will need to do this in the create callback then, and use the update callback only for updating this observable.

**Comment by Anber** [comment]
If create callback can return observable, then why can not update?

In my case enough 'create', but this can be useful to someone.

**Comment by sagacity** [comment]
The reason is that the 'create' callback should be the only one that actually creates new observables.
The 'update' callback should only update existing objects.

That's why they are separated like this.

Is this enough information for now? I'll go ahead and close the issue, if you need more assistance feel free to reopen this issue or, preferably, post something on the KnockoutJS google group where more people can participate in the discussion.

The group can be found here: https://groups.google.com/forum/?fromgroups#!forum/knockoutjs
