### ISSUE TITLE
Handle mapping of arrays of primitive types (like arrays of strings)

### ISSUE THREAD

**Issue by mackd** [SteveSanderson/knockout.mapping#42]
When mapping an object with something like this:

``` javascript
{
    /* other properties... */

    test: ["string 1", "string 2"]
}
```

My intuitive expectation is that this will be mapped to an array of observables, but this is not happening.

I hacked a local copy to get it working how I expected.  See my patch at mackd/knockout.mapping@6cf9a53f615e6e80820d644a808269f328a69f42

**Comment by sagacity** [comment]
This is by design, only properties that are part of an object get mapped.

The pull request is certainly welcome, but would it be possible for you to also include a mapping option to allow others to 'opt in' to this behavior so that they won't get surprised when they update the plugin? Also, can you add the relevant tests?
