### ISSUE TITLE
toJS returns empty object in array after splice

### ISSUE THREAD

**Issue by wjbryant** [SteveSanderson/knockout.mapping#74]
Splicing an item into an observable array created using fromJS causes toJS to return an empty item in the array. This was originally created as an issue for the knockout-sortable plugin: https://github.com/rniemeyer/knockout-sortable/issues/17

Here is an example that demonstrates the problem in more detail: http://jsfiddle.net/WDrep/9/

**Comment by sagacity** [comment]
This is due to the way the plugin stores which items have already been mapped and which have not been mapped (inside the `__ko_mapping__` property in `mappedObject`).

The idea is that if you want to add new items you would do this through an update with `fromJS` or by using `mappedCreate`.

**Comment by wjbryant** [comment]
I see. So is it possible to change the order of an observable array created with fromJS? Should I not be using the splice, sort, push, etc. methods when using the mapping plugin?

I tried `mappedObject.items.mappedCreate({name: 'item 4'});` to add an item, but it exhibited the same issue. `mappedObject.items.push(ko.mapping.fromJS({name: 'item 4'}));` seems to work, but I'm not sure if that's the right way to do it.

Thanks for your help,
Bill

**Comment by sagacity** [comment]
Your 'workaround' using `fromJS` is completely valid and that's pretty much the intended use. However, when you splice in a copy of another mapped object then the system gets confused. In your workaround however you are creating a new mapped object and inserting that. That should work fine.

The `mappedCreate` is a convenience function that only works when you have a `create` callback, otherwise it inserts your unmapped object in the array. That's odd behavior and I'm thinking about removing this functionality entirely.

Does that make things a bit clearer?

**Comment by wjbryant** [comment]
Thanks. That's very helpful. My only other question then is - is there a safe way to move an item from one position to another without confusing the system? That's originally what I was trying to accomplish using the knockout-sortable plugin.

**Comment by sagacity** [comment]
To be honest I'm also currently using the sortable plugin without any of these issues, which makes it doubly odd.

However, the difference is that I'm using the `create` callback to create the separate items in my array, like so:

``` javascript
var mapping = {
  items: {
    create: function(data) {
      return new MyItem(data.data);
    }
  }
};
```

Maybe you could give that approach a shot, just as a test?

**Comment by wjbryant** [comment]
Thanks for the tip! That works perfectly! I modified my original example using the sortable plugin to use the create callback and that small change fixed the problem.

Original version (does not work): http://jsfiddle.net/WDrep/2/
Modified version (with create callback): http://jsfiddle.net/WDrep/11/

I would have never thought that would make a difference. Thanks for your help!

**Comment by sagacity** [comment]
You're welcome!

**Comment by vantreeseba** [comment]
I didn't see this issue when I commented on #65.

On the mappedCreate callback, and perhaps the push itself, we could wrap the value inserted into the array by default with a call to ko.mapping.fromJS().  This isn't super elegant, but it would fix any confusion with adding objects to mapped arrays.  

It would cause any object added to a mapped array to behave "as expected" in that the full object added would always get returned, instead of returning an empty object.
