### ISSUE TITLE
IE mime issue VS jsFiddle

### ISSUE THREAD

**Issue by ScottIngram** [SteveSanderson/knockout.mapping#97]
While testing some knockout stuff on jsFiddle 
http://jsfiddle.net/singram/WUCgc/

Internet Explorer complained:

SEC7112: Script from https://raw.github.com/SteveSanderson/knockout.mapping/master/build/output/knockout.mapping-latest.debug.js  was blocked due to mime type mismatch

**Comment by cspotcode** [comment]
I think this is Github's fault.  The mime type is sent from the server to your browser in the HTTP headers.  Since IE was trying to download a script, it expected the "text/javascript" mime-type.  However, raw.github.com sends the "text/plain" mime-type.

As far as I know, there's no way to fix this issue by changing the Javascript source itself.

**Comment by sagacity** [comment]
Agreed, I'm not sure how to fix that. Having said that, jsfiddle+github seems to work fine in other browsers, maybe there's an IE workaround as well.

**Comment by ScottIngram** [comment]
Sorry, I should have linked to this thread dealing with the same problem for knockout itself...
https://github.com/SteveSanderson/knockout/issues/585

The solution was to link to a copy of the file that exists outside of raw.github.com.
